### ISSUE TITLE
Error in installing MEAN.io in Ubuntu14.04

### ISSUE THREAD

**Issue by Keerthana17** [linnovate/meanio#77]
:~$ sudo npm install -g meanio@latest
/
> mean-health@0.1.7 postinstall /usr/lib/node_modules/meanio/node_modules/mean-health
> node ./postinstall.js

npm WARN engine postcss@5.0.10: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
-
> meanio@0.8.82 postinstall /usr/lib/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm ERR! Error: Attempt to unlock ., which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/lib/node_modules/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/lib/node_modules/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:16:25)
npm ERR!     at afterMkdir (/usr/lib/node_modules/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-65-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /usr/lib/node_modules/meanio/lib/core_modules/server
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/lib/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! not ok code 0

npm ERR! meanio@0.8.82 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.8.82 postinstall script.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-65-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "meanio@latest"
npm ERR! cwd /home/minerva
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by Keerthana17** [comment]
Tried a couple of times, still same result. No luck with "sudo npm install -g mean-cli" either. Help, please ?

**Comment by liorkesos** [comment]
Paste the sudo npm install -g mean-cli

**Comment by ilpise** [comment]
I'm on Ububtu 14.04.
I've installed node version 4 following the instruction [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
I'm using the 4 version, not the 6 version, because the 4 version it seems to be the LTS.

After the installation check the node version from a console 
`$ node --version`
`v4.4.7`
Then I've installed npm
`$ sudo npm install npm -g`
the version I've now is
`$ npm --version`
`3.10.5`

Then I've installed mean-cli
`$ sudo npm install -g mean-cli `
and initiated a new application
` $ mean init yourNewApp`

from inside the yourNewApp folder I've runned `node install`

I had some error - look at the invalid packages

> ├─┬ meanio@0.9.3
│ └─┬ express-jwt@3.4.0
│   └── jsonwebtoken@5.7.0 
├─┬ meanio-admin@0.1.6  invalid (git://github.com/linnovate/meanio-admin.git#66b03424a94cf51199ba21b5f2ac1d9eefa9e0aa)
│ ├── meanio-circles@0.1.1  (git://github.com/linnovate/meanio-circles.git#10e8982d280488c4c751ccb4da089d8ffff1cb6f)
│ └── meanio-users@0.1.4  (git://github.com/linnovate/meanio-users.git#79dacf5194d2cfa1676ac5ac59066138db37f74d)
└── meanio-system@0.1.3  invalid (git://github.com/linnovate/meanio-system.git#a1b1b2b35eec858493d3a308e56d1e2014627ed5)

but I've solved installing the latest version
`$ npm install meanio-admin`
`$ npm install meanio-system`

launching gulp everything is working correctly
